version: 2
jobs:
  build:
    working_directory: ~/attraction-wars-server
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint

  build-image:
    environment:
      IMAGE_NAME: "$IMAGE_NAME"
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
    filters:
      branches:
        only: develop
    requires:
      - lint

  publish:
    environment:
      IMAGE_NAME: "$IMAGE_NAME"
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
    requires:
      - build-image
    filters:
      branches:
        only: develop
